# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java Build with Maven

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Setup AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli
    - name: Set environment variables
      run: |
        echo "SMTP_PWD=${{ secrets.SMTP_PWD }}" >> $GITHUB_ENV
        echo "SMTP_USRNME=${{ secrets.SMTP_USRNME }}" >> $GITHUB_ENV
        echo "DB_URL=${{ secrets.DB_URL }}" >> $GITHUB_ENV
        echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> $GITHUB_ENV
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV
    - name: Build with Maven
      run: mvn clean package
    - name: Configure AWS Access Credentials
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
        aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
        aws configure set default.region us-east-1
    - name: Transfer the jar file to S3 bucket
      env:
        BUCKET_NAME: crmnew-artifact
        FILE_PATH: target/crm-new.jar
        S3_PATH: crm-new.jar
      run: |
        aws s3 cp $FILE_PATH s3://$BUCKET_NAME/$S3_PATH
    - name: Setup PEM File
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > key.pem
        chmod 600 key.pem
    - name: Download the jar file from S3
      env:
        USERNAME: ${{ secrets.SSH_USERNAME }}
        SERVER: ${{ secrets.SSH_SERVER }}
        BUCKET_NAME: crmnew-artifact
      run: |
        ssh -i key.pem -o StrictHostKeyChecking=no $USERNAME@$SERVER 'aws s3 cp s3://crmnew-artifact/crm-new.jar /home/ubuntu/crm-deploy/crm-new.jar'
    - name: Run application
      env:
        USERNAME: ${{ secrets.SSH_USERNAME }}
        SERVER: ${{ secrets.SSH_SERVER }}
        SMTP_PWD: ${{ secrets.SMTP_PWD }}
        SMTP_USRNME: ${{ secrets.SMTP_USRNME }}
        DB_URL: ${{ secrets.DB_URL }}
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      run: |
        ssh -i key.pem -o StrictHostKeyChecking=no $USERNAME@$SERVER 'export SMTP_PWD="${{ secrets.SMTP_PWD }}" SMTP_USRNME="${{ secrets.SMTP_USRNME }}" DB_URL="${{ secrets.DB_URL }}" DB_USERNAME="${{ secrets.DB_USERNAME }}" DB_PASSWORD="${{ secrets.DB_PASSWORD }}"; nohup java -Xms256m -Xmx1024m -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/home/ubuntu/crm-deploy -jar /home/ubuntu/crm-deploy/crm-new.jar > /home/ubuntu/crm-deploy/crm-new.log 2>&1 &'
        
