# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java Build with Maven

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Setup AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli
    - name: Set environment variables
      run: |
        echo "SMTP_PWD=${{ secrets.SMTP_PWD }}" >> $GITHUB_ENV
        echo "SMTP_USRNME=${{ secrets.SMTP_USRNME }}" >> $GITHUB_ENV
        echo "DB_URL=${{ secrets.DB_URL }}" >> $GITHUB_ENV
        echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> $GITHUB_ENV
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV
    - name: Build with Maven
      run: mvn clean package
    - name: Configure AWS Access Credentials
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
        aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
        aws configure set default.region us-east-1
    - name: Transfer the jar file to S3 bucket
      env:
        BUCKET_NAME: crmnew-artifact
        FILE_PATH: target/crm-new.jar
        S3_PATH: crm-new.jar
      run: |
        aws s3 cp $FILE_PATH s3://$BUCKET_NAME/$S3_PATH
        
